<a href="https://colab.research.google.com/github/khyz/AI_Python_examples/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
help(np.array)

In [ ]:
x = np.array([1,3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x=np.array([1.2,3.3,4.4])

In [ ]:
x.dtype

dtype('float64')

In [ ]:
d2 = np.array([[1,2],[3,23]])

In [ ]:
print(d2)

[[ 1  2]
 [ 3 23]]


In [ ]:
d2.ndim

2

In [ ]:
d2.shape

(2, 2)

In [ ]:
x = np.array([[1,2,3],[1,2,4]])

In [ ]:
x.shape


(2, 3)

In [ ]:
print(x)

[[1 2 3]
 [1 2 4]]


In [ ]:
x = np.array([[[4,4,4],
               [1,1,2]],

              [[4,4,2],
              [4,1,2]]])#to macierz 3d - wyobraź to sobie jako dwie tablice umieszczone w przestrzeni (prostopadłościan)

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 2)

In [ ]:
a = np.array([1,3,4],dtype='float')#zmiana typu domyślnego przez dodanie argumentu dtype do funkcji

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a = np.array([1,3,4],dtype='complex')#zmiana typu domyślnego na compex -

In [ ]:
a.dtype

dtype('complex128')

In [ ]:
a = np.array([1.1,3.1,41.6],dtype='int')#zmiana typu domyślnego na int, czyli w tym przypadku konwersja stratna!

In [ ]:
print(a)

[ 1  3 41]


In [ ]:
a = np.array([True, False])

In [ ]:
a = np.array([24,120,254], dtype=np.int8) #czasem wystarczy int 8 bitowy (0-255) i warto o tym pamiętać

<ipython-input-45-d9ebd32ce9fe>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 254 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.array([24,120,254], dtype=np.int8) #czasem wystarczy int 8 bitowy (0-255) i warto o tym pamiętać


In [ ]:
a = np.array([24,120,254], dtype=np.uint8) #czasem wystarczy int 8 bitowy (0-255) i warto o tym pamiętać (np. do obrazów)

Tworzenie tablic

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(3,4), dtype='int')#zmiana na int bo domyślnie jest float

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones(shape=(4,4))# domyślnie jest float

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#można też wypełnić tablicę dowolnymi wartościami
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
# w zwykłym pythonie3
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(10)#generuje liczby od 0-9 w tablicy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5,stop=11) #warto zwrócić uwagę, że ostatni parametr nie został dodany do tablicy

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(start=5,stop=100, step=10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [ ]:
np.arange(start=105,stop=10, step=-10) #malejąco

array([105,  95,  85,  75,  65,  55,  45,  35,  25,  15])

In [ ]:
np.arange(start=5,stop=8, step=0.50)

array([5. , 5.5, 6. , 6.5, 7. , 7.5])

In [ ]:
np.linspace(start=5,stop=8, num=11)#11 równo rozłożonych liczb od 5 do 8

array([5. , 5.3, 5.6, 5.9, 6.2, 6.5, 6.8, 7.1, 7.4, 7.7, 8. ])

In [ ]:
A = np.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3,-1))#argument -1 powoduje automatyczne dobranie rozmiaru tablicy o 3 wierszach (bo tyle wierszy podaliśmy!)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1,5))#argument -1 powoduje automatyczne dobranie ilości wierszy (podaliśmy ile argumentów jest w elemencie)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Podstawowe operacje na tablicach

In [ ]:
A=np.array([3,1,4,2])
B=np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A+B

array([6, 0, 7, 4])

In [ ]:
A-B

array([0, 2, 1, 0])

In [ ]:
A*B

array([ 9, -1, 12,  4])

In [ ]:
A/B#przy okazji konwertuje na float

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A+3

array([6, 4, 7, 5])

In [ ]:
2*A

array([6, 2, 8, 4])

In [ ]:
A+3*B

array([12, -2, 13,  8])

In [ ]:
#są też konkretne komendy
np.add(A,B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [ ]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
#mnożenie macieżowe
x = np.array([[1,3],[-2,0]])
y = np.array([[1,3],[3,4]])
print(x,'\n')
print(y)

[[ 1  3]
 [-2  0]] 

[[1 3]
 [3 4]]


In [ ]:
x*y#to nie jest mnożenie macierzy z algebry!

array([[ 1,  9],
       [-6,  0]])

In [ ]:
np.dot(x,y)#mnożenie macierzy!

array([[10, 15],
       [-2, -6]])

In [ ]:
x.dot(y)

array([[10, 15],
       [-2, -6]])

In [ ]:
y.dot(x)#mnożenie macierzy nie jest przemienne!

array([[-5,  3],
       [-5,  9]])

In [ ]:
x@y  #bardzo ciekawe !

array([[10, 15],
       [-2, -6]])

Liczby pseudolosowe

In [4]:
np.random.seed(0)

In [5]:
np.random.randn()

1.764052345967664

In [6]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [7]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [8]:
np.random.rand(10)

array([0.19658236, 0.36872517, 0.82099323, 0.09710128, 0.83794491,
       0.09609841, 0.97645947, 0.4686512 , 0.97676109, 0.60484552])

In [9]:
np.random.rand(10,2)

array([[0.73926358, 0.03918779],
       [0.28280696, 0.12019656],
       [0.2961402 , 0.11872772],
       [0.31798318, 0.41426299],
       [0.0641475 , 0.69247212],
       [0.56660145, 0.26538949],
       [0.52324805, 0.09394051],
       [0.5759465 , 0.9292962 ],
       [0.31856895, 0.66741038],
       [0.13179786, 0.7163272 ]])

In [11]:
np.random.randint(10)

6

In [12]:
np.random.randint(low=10,high=101)

29

In [13]:
np.random.randint(low=10,high=101, size=10)

array([56, 52, 66, 70, 87, 40, 34, 12, 13, 23])

In [16]:
np.random.choice([4,2,1,5,10])

4

In [17]:
np.random.choice(['python','java','sql','rad'])

'python'

In [19]:
data = np.arange(10)

In [21]:
np.random.shuffle(data)

In [22]:
data #dane zostały zmienione! nie trzeba przypisywać ich do innej zmiennej.
      # Jednocześnie, jeśli chcemy zachować pierwotne dane, to musimy je skopiować.

array([8, 0, 1, 9, 3, 7, 2, 6, 5, 4])

In [23]:
np.exp(1)

2.718281828459045

In [24]:
np.sqrt(4)#zawsze float

2.0

In [25]:
np.all([2,1,2])#zwraca true, bo wszytkie elementy są true

True

In [26]:
np.all([2,0,1,1,1])#zwraca bo pojawiło się 0/wartość false

False

In [27]:
np.any([1,1,1,1])

True

In [28]:
np.any([0,0,0,1])#jedna z wartości to true

True

In [29]:
np.any([0,0,0,0])#żadne z wartości nie jest true

False

In [30]:
bool(1.2)

True

In [31]:
bool(0.9)

True

In [32]:
bool(0)

False

In [33]:
A=np.random.rand(5)

In [34]:
np.argmax(A)#zwraca który argument w kolejności jest największy

3

In [35]:
print(A)

[0.39650574 0.8811032  0.58127287 0.88173536 0.69253159]


In [36]:
A[np.argmax(A)]# zwraca wartość argumentu

0.8817353618548528

In [37]:
np.argmin(A)#to samo ale dla minimum/

0

In [38]:
np.argsort(A)

array([0, 2, 4, 1, 3])

In [41]:
#proste
np.max(A)
np.min(A)

0.39650574084698464

In [42]:
np.mean(A)

0.6866297525053248

In [43]:
np.median(A)

0.6925315900777659

In [44]:
np.std(A)

0.18503673441768229

Indeksowanie, wycinanie

In [7]:
A=np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
#A[index], A[start:stop], A[:stop], A[start:]
A[2]

2

In [47]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [48]:
A[:2]

array([0, 1])

In [49]:
A[-1]

19

In [57]:
A[10:15]

array([10, 11, 12, 13, 14])

In [8]:
A=A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
A[0]#wycinam cały pierwszy wiersz

array([0, 1, 2, 3, 4])

In [9]:
A[:-1]#wyciecie przeostatniej kolumny

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
A[1,3]

8

In [11]:
A[1:3,1:4]#wycinanie części tablicy

array([[ 6,  7,  8],
       [11, 12, 13]])

In [12]:
A[1,2]=14
A#zmiana pewnego argumentu w tablicy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [14]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [15]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [16]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [17]:
A.shape

(4, 5)

In [18]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [19]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
A.T#tablica transponowana

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [23]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10,-1)

A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [24]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [25]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [26]:
np.bitwise_and(A>-5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [27]:
np.bitwise_or(A<-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])